# =============================================================================
# BRAWL BYTES - MASTER GAME CONSTANTS
# =============================================================================
# Single source of truth for ALL game configuration
# Run `npm run sync-constants` to push changes to database
# 
# Categories:
# - physics: Core game physics and movement
# - combat: Damage, timing, and attack mechanics  
# - characters: All character stats and abilities
# - stages: Stage layouts, platforms, and visual config
# - scenes: Phaser scene identifiers
# - assets: Asset keys and file paths
# - game: Match rules and gameplay settings
# - ui: Colors, fonts, and interface styling
# - network: Multiplayer synchronization settings
# - validation: Server-side validation tolerances
# - player: Player entity configuration
# - animation: Visual effect timings and scales
# - server: Server configuration
# =============================================================================

# PHYSICS CONSTANTS
# Core movement, gravity, and world boundaries
physics:
  gravity: 800
  jump_velocity: -600
  double_jump_velocity: -500
  move_speed: 300
  max_velocity: 1000
  max_acceleration: 500
  friction: 0.8
  air_resistance: 0.95
  bounce_factor: 0.3
  walking_threshold: 50
  double_jump_multiplier: 0.85
  world_bounds:
    width: 2000
    height: 1200
    min_x: -2000
    max_x: 2000
    min_y: -2000
    max_y: 1200
    death_zone_y: 1300
  collision:
    player_radius: 16
    stage_thickness: 20

# COMBAT SYSTEM
# Damage calculations, attack timing, and combat mechanics
combat:
  fall_damage: 5
  max_damage_per_hit: 50
  min_damage_per_hit: 5
  critical_multiplier: 1.5
  critical_chance: 0.1
  attack_cooldown: 500
  invulnerability_duration: 1000
  critical_invulnerability_duration: 1500
  respawn_invulnerability: 3000
  flash_interval: 100
  max_combo_time: 2000
  attack_range: 80
  max_knockback_velocity: 800

# CHARACTER ROSTER
# All playable characters with complete stat definitions
characters:
  dash:
    id: "dash"
    name: "Dash"
    description: "A lightning-fast fighter who relies on speed and agility"
    type: "DASH"
    stats:
      health: 80
      speed: 400
      jump_velocity: -650
      attack_damage: 15
      weight: 70
      defense: 60
      special_attack_damage: 25
    abilities:
      - "Lightning Strike"
      - "Speed Boost" 
      - "Dash Attack"
    unlock_requirements:
      level: 1
      wins: 0
      cost: 0
    
  rex:
    id: "rex"
    name: "Rex"
    description: "A well-balanced all-around fighter with solid stats"
    type: "REX"
    stats:
      health: 100
      speed: 300
      jump_velocity: -600
      attack_damage: 20
      weight: 85
      defense: 80
      special_attack_damage: 30
    abilities:
      - "Power Strike"
      - "Shield Block"
      - "Combo Rush"
    unlock_requirements:
      level: 1
      wins: 0
      cost: 0
      
  titan:
    id: "titan"
    name: "Titan"
    description: "A heavy-hitting tank with massive damage and health"
    type: "TITAN"
    stats:
      health: 130
      speed: 200
      jump_velocity: -500
      attack_damage: 30
      weight: 120
      defense: 100
      special_attack_damage: 45
    abilities:
      - "Ground Pound"
      - "Heavy Slam"
      - "Rage Mode"
    unlock_requirements:
      level: 1
      wins: 0
      cost: 0

  ninja:
    id: "ninja"
    name: "Ninja"
    description: "A stealthy assassin with mobility and precision strikes"
    type: "DASH"
    stats:
      health: 75
      speed: 450
      jump_velocity: -700
      attack_damage: 18
      weight: 65
      defense: 50
      special_attack_damage: 35
    abilities:
      - "Shadow Strike"
      - "Teleport"
      - "Smoke Bomb"
    unlock_requirements:
      level: 5
      wins: 10
      cost: 500

# STAGE CONFIGURATIONS
# All battle arenas with platforms, hazards, and visual settings
stages:
  battle_arena:
    id: "battle_arena"
    name: "Rainforest Arena"
    description: "A lush jungle arena with wooden platforms and dense vegetation"
    difficulty: "Easy"
    config:
      platforms:
        - { x: 1000, y: 1100, width: 10, height: 1 }  # Main platform (ground level)
        - { x: 400, y: 840, width: 4, height: 1 }     # Left platform (reachable)
        - { x: 1600, y: 840, width: 4, height: 1 }    # Right platform (reachable)
        - { x: 1000, y: 675, width: 3, height: 1 }    # Center elevated (accessible with single jump)
        - { x: 600, y: 450, width: 2, height: 1 }     # Top left (accessible with single jump)
        - { x: 1400, y: 450, width: 2, height: 1 }    # Top right (accessible with single jump)
      hazards: []
      background_colors:
        top: 0x1a4a3a
        bottom: 0x4caf50
      music: "battle_theme"
    unlock_requirements:
      level: 1
      wins: 0
      cost: 0
      
  floating_islands:
    id: "floating_islands"
    name: "Floating Islands"
    description: "Scattered platforms floating in the sky"
    difficulty: "Medium"
    config:
      platforms:
        - { x: 1000, y: 1000, width: 6, height: 1 }   # Main platform
        - { x: 300, y: 700, width: 2, height: 1 }     # Far left
        - { x: 700, y: 500, width: 2, height: 1 }     # Mid left
        - { x: 1300, y: 500, width: 2, height: 1 }    # Mid right
        - { x: 1700, y: 700, width: 2, height: 1 }    # Far right
        - { x: 1000, y: 300, width: 3, height: 1 }    # Top center
      hazards: []
      background_colors:
        top: 0x4169e1
        bottom: 0x87cefa
      music: "sky_theme"
    unlock_requirements:
      level: 3
      wins: 5
      cost: 200
      
  volcanic_chamber:
    id: "volcanic_chamber"
    name: "Volcanic Chamber"
    description: "A dangerous stage with lava hazards"
    difficulty: "Hard"
    config:
      platforms:
        - { x: 1000, y: 1000, width: 8, height: 1 }   # Main platform
        - { x: 500, y: 700, width: 2, height: 1 }     # Left platform
        - { x: 1500, y: 700, width: 2, height: 1 }    # Right platform
        - { x: 1000, y: 400, width: 3, height: 1 }    # Center elevated
      hazards:
        - { type: "lava", x: 200, y: 1150, width: 200, height: 50 }
        - { type: "lava", x: 1600, y: 1150, width: 200, height: 50 }
      background_colors:
        top: 0x8b0000
        bottom: 0xff4500
      music: "volcano_theme"
    unlock_requirements:
      level: 8
      wins: 20
      cost: 800

# PHASER SCENE IDENTIFIERS
# All scene keys used throughout the application
scenes:
  boot: "BootScene"
  menu: "MenuScene"
  character_select: "CharacterSelectScene"
  stage_select: "StageSelectScene"
  game: "GameScene"
  result: "ResultScene"
  lobby: "LobbyScene"

# ASSET MANAGEMENT
# All game assets organized by type
assets:
  # Note: Currently using frontend-served assets and placeholders
  # Future: Add base_url when implementing full asset system
  
  images:
    logo: "logo"  # Using jungle-themed placeholder
    background_menu: "background_menu"  # Jungle video served from frontend
    background_stage1: "background_stage1"  # Future: jungle backgrounds
    background_stage2: "background_stage2"  # Future: jungle backgrounds
    background_stage3: "background_stage3"  # Future: jungle backgrounds
    character_dash: "character_dash"  # Now uses dash_spritesheet.png
    character_rex: "character_rex"  # Now uses rex_spritesheet.png
    character_titan: "character_titan"  # Using jungle-themed placeholder
    character_ninja: "character_ninja"  # Now uses ninja_spritesheet.png
    dash_card: "dash_card"  # Dash character card image
    ninja_card: "ninja_card"  # Ninja character card image
    rex_card: "rex_card"  # Rex character card image
    titan_card: "titan_card"  # Titan character card image
    platform: "platform"  # Keep existing
    ui_button: "ui_button"  # Using jungle-themed placeholder
    ui_button_hover: "ui_button_hover"  # Using jungle-themed placeholder
    health_bar: "health_bar"  # Keep existing
    energy_bar: "energy_bar"  # Keep existing
  
  audio:
    menu_music: "menu_music"  # Future: jungle ambient
    game_music: "game_music"  # Keep existing
    battle_theme: "battle_theme"  # Keep existing
    sky_theme: "sky_theme"  # Keep existing
    volcano_theme: "volcano_theme"  # Keep existing
    sfx_jump: "sfx_jump"  # Keep existing
    sfx_attack: "sfx_attack"  # Keep existing
    sfx_hit: "sfx_hit"  # Keep existing
    sfx_button: "sfx_button"  # Future: wooden click
    sfx_victory: "sfx_victory"  # Keep existing
    sfx_defeat: "sfx_defeat"  # Keep existing
  
  spritesheets:
    dash_sprites: "dash_sprites"      # Using actual dash_spritesheet.png
    rex_sprites: "rex_sprites"        # Using actual rex_spritesheet.png
    titan_sprites: "titan_sprites"    # Using placeholder for now
    ninja_sprites: "ninja_sprites"    # Using actual ninja_spritesheet.png
    effects: "effects_sprites"        # Future: effects spritesheet
    ui_elements: "ui_sprites"         # Future: UI elements spritesheet

# GAME RULES
# Match settings and gameplay parameters
game:
  max_stocks: 3
  match_time: 180000  # 3 minutes in milliseconds (server uses 180 seconds)
  respawn_time: 3000
  max_players: 4
  min_players: 2
  sudden_death_time: 60000
  default_max_players: 2
  default_time_limit: 300  # 5 minutes in seconds
  victory_conditions:
    - "last_player_standing"
    - "most_stocks_remaining"
    - "highest_damage_dealt"

# USER INTERFACE
# Colors, fonts, and styling configuration
ui:
  colors:
    primary: "#4caf50"        # Jungle Green
    secondary: "#1a4a3a"      # Deep Forest Green
    success: "#66bb6a"        # Light Green
    danger: "#c62828"         # Vine Red
    warning: "#f9a825"        # Bamboo Gold
    text: "#ffffff"           # White (keep)
    text_secondary: "#a5d6a7" # Light Forest Green
    background: "#2e5230"     # Dark Forest
    accent: "#ff6f00"         # Tribal Orange
    # Character type colors for sprite tinting
    character_dash: "#27ae60"        # Green for fast/lightweight
    character_rex: "#3498db"         # Blue for balanced/allrounder  
    character_titan: "#e74c3c"       # Red for heavy/hitter
    character_ninja: "#9b59b6"       # Purple for stealth
  
  fonts:
    primary: "Arial, sans-serif"
    secondary: "monospace"
    heading: "Georgia, serif"
  
  dimensions:
    button_width: 200
    button_height: 50
    health_bar_width: 200
    health_bar_height: 20
    character_portrait_size: 80

# NETWORKING
# Multiplayer synchronization and communication settings
network:
  position_sync_rate: 60  # FPS
  max_input_buffer_size: 120
  interpolation_delay: 100
  max_buffer_size: 1000
  heartbeat_interval: 30000
  connection_timeout: 10000
  max_reconnect_attempts: 3
  
# SOCKET EVENTS
# All WebSocket event names centralized
socket_events:
  # Authentication
  authenticate: 'authenticate'
  authenticated: 'authenticated'
  
  # Game events
  player_input: 'playerInput'
  player_joined: 'playerJoined'
  player_left: 'playerLeft'
  match_end: 'matchEnd'
  match_found: 'matchFound'
  
  # Room events
  room_joined: 'roomJoined'
  lobby_state: 'lobbyState'
  queue_joined: 'queueJoined'
  
  # Error events
  error: 'error'
  disconnect: 'disconnect'
  
# ERROR MESSAGES
# Standardized error messages
error_messages:
  # Authentication errors
  must_be_authenticated: 'Must be authenticated'
  invalid_credentials: 'Invalid credentials'
  invalid_token: 'Invalid token'
  invalid_email_format: 'Invalid email format'
  
  # Game room errors
  not_in_game_room: 'Not in a game room'
  stage_must_be_selected: 'Stage must be selected'
  cannot_start_game: 'Cannot start game'
  
  # Configuration errors
  reconnection_grace_period_required: 'reconnectionGracePeriod is required in game configuration'
  max_reconnection_time_required: 'maxReconnectionTime is required in game configuration'
  max_disconnect_count_required: 'maxDisconnectCount is required in game configuration'
  auto_cleanup_on_timeout_required: 'autoCleanupOnTimeout is required in game configuration'
  corrected_state_position_required: 'Corrected state must have a position'
  corrected_state_velocity_required: 'Corrected state must have a velocity'
  canstart_reason_required: 'canStart must provide a reason when canStart is false'
  spawn_point_required: 'Scene must provide spawn point coordinates'
  jump_type_required: 'Jump type is required for jump input'
  special_type_required: 'Special type is required for special input'
  socket_url_required: 'VITE_SOCKET_URL environment variable is required'
  
# API ENDPOINTS
# All API endpoint paths
api_endpoints:
  base_url: 'http://localhost:3001'
  frontend_url: 'http://localhost:3000'
  
  # API routes
  constants: '/api/constants'
  characters: '/api/characters'
  stages: '/api/stages'
  
  # Auth routes
  register: '/register'
  login: '/login'
  refresh: '/refresh'
  profile: '/profile'
  
  # Game routes
  game_constants_root: '/'
  game_constants_category: '/:category'
  game_constants_name: '/:category/:name'
  
# ASSET PATHS
# All asset file paths
asset_paths:
  # Video backgrounds
  jungle_canopy: '/assets/backgrounds/jungle-canopy.mp4'
  ancient_colosseum: '/assets/backgrounds/ancient-colosseum.mp4'
  map_table: '/assets/backgrounds/map-table.mp4'
  jungle_clearing: '/assets/backgrounds/jungle-clearing.mp4'
  
  # Character spritesheets
  dash_spritesheet: '/assets/dash_spritesheet.png'
  rex_spritesheet: '/assets/rex_spritesheet.png'
  ninja_spritesheet: '/assets/ninja_spritesheet.png'
  titan_spritesheet: '/assets/titan_spritesheet.png'
  
  # Character cards
  dash_card: '/assets/dash_card.jpg'
  rex_card: '/assets/rex_card.jpg'
  ninja_card: '/assets/ninja_card.jpg'
  titan_card: '/assets/titan_card.jpg'
  
# ENVIRONMENT VARIABLES
# All environment variable names
env_vars:
  jwt_secret: 'JWT_SECRET'
  node_env: 'NODE_ENV'
  port: 'PORT'
  frontend_url: 'FRONTEND_URL'
  socket_url: 'VITE_SOCKET_URL'
  
# DATABASE MAPPING
# Database table and column names
database:
  table_mappings:
    created_at: 'created_at'
    updated_at: 'updated_at'
    user_id: 'user_id'
    character_id: 'character_id'
    stage_id: 'stage_id'

# SERVER VALIDATION
# Anti-cheat and movement validation tolerances
validation:
  position_tolerance: 5.0
  velocity_tolerance: 50.0
  max_position_change_per_ms: 100.0
  max_velocity_change_per_ms: 500.0
  damage_validation_window: 1000
  input_validation_strictness: 0.8
  max_ping_ms: 200

# PLAYER ENTITY
# Player collision and display configuration
player:
  collision_box:
    width: 32
    height: 48
  display_size:
    width: 64
    height: 96
  radius: 16
  hitbox_offset:
    x: 0
    y: -8

# ANIMATION SYSTEM
# Visual effects timing and scaling
animation:
  breathing_scale:
    scale_y: 1.05
    duration: 2000
  hit_effect:
    scale_y: 1.2
    duration: 200
  damage_effect:
    scale_y: 0.8
    duration: 300
  victory_animation:
    duration: 3000
  defeat_animation:
    duration: 2000

# SERVER CONFIGURATION
# Port settings and server behavior
server:
  port: 3001
  frontend_port: 5173
  max_rooms: 100
  max_players_per_room: 4
  room_timeout: 300000  # 5 minutes
  cleanup_interval: 60000  # 1 minute
  reconnection_grace_period: 30000  # 30 seconds
  max_reconnection_time: 120000  # 2 minutes
  max_disconnect_count: 5
  auto_cleanup_on_timeout: true
  cache_duration: 60000  # 1 minute
  
# MAGIC NUMBERS AND CONSTANTS
# Previously hardcoded values now centralized
magic_numbers:
  # Player spawn and physics
  default_spawn_position:
    x: 1000
    y: 1000
  default_health: 100
  default_stocks: 3
  ground_detection_threshold: 0
  
  # Attack and combat
  attack_hitbox:
    width: 80
    height: 60
  attack_feedback_delay: 100
  damage_shake_duration: 200
  fall_animation_duration: 300
  knockback_force:
    y: -150
  
  # UI and visual
  reconciliation_threshold: 5
  drag_multiplier: 1000
  body_offset:
    x: 5
    y: 5
  sprite_origin:
    x: 0.5
    y: 1.0
  alpha_invulnerable: 0.5
  
  # Stage selection UI
  stage_card:
    width: 240
    height: 320
    spacing: 40
    start_y: 250
  grid_spacing: 50
  title_y_position: 80
  stroke_width: 4
  shadow_offset: 2
  ui_depth: 1000
  notification_depth: 999
  ui_positioning_offset: 20
  ui_rectangle_height: 100
  ui_rectangle_color: 0x333333
  ui_rectangle_alpha: 0.9
  
  # Timing and intervals
  countdown_duration: 3000
  timer_delay: 1000
  fade_animation_duration: 300
  grace_period_buffer: 1000
  
  # Physics update rates
  physics_update_rate: 60  # FPS
  physics_interval: 16.67  # 1000/60
  
  # Player statistics
  base_experience: 50
  duration_bonus_max_minutes: 10
  duration_bonus_multiplier: 2
  base_coins: 25
  experience_coin_multiplier: 0.5
  elo_k_factor: 32
  default_expected_score: 0.5
  elo_rating_divisor: 400
  level_calculation_divisor: 100
  
  # Rank thresholds
  rank_thresholds:
    diamond: 2000
    platinum: 1700
    gold: 1400
    silver: 1100
    bronze: 800
    
  # Grid line styling
  grid_line:
    width: 1
    color: 0xe74c3c
    alpha: 0.1